### ISSUE TITLE
Paper typos and suggestions

### ISSUE THREAD

**Issue by chad-earthscope** [savage13/sacio#2]
- "seismoloigical" -> seismological

- "restrited" -> restricted, may also consider writing "export-restricted"

- "used by seismologist globally" -> "seismologists" (plural)

- Inconsistent use of "meta-data" and "meta data", personally I prefer "metadata"

- "2 Clause" -> "2-Clause" or "2-clause"

**Comment by danielskatz** [comment]
openjournals/joss-reviews#3619
