### ISSUE TITLE
Link or show References for paper.md file

### ISSUE THREAD

**Issue by mbegnaud** [savage13/sacio#9]
A link to the references or the actual references need to be shown for the paper.md file. 

openjournals/joss-reviews#3619

**Comment by danielskatz** [comment]
I don't think I understand this.  Can you be more specific?

I wonder if you are looking at the difference between [paper.md](https://github.com/savage13/sacio/blob/master/paper/paper.md), which is source that doesn't have a references section, and the built paper (currently https://github.com/openjournals/joss-papers/blob/joss.03619/joss.03619/10.21105.joss.03619.pdf), which does have the full references.

**Comment by mbegnaud** [comment]
@danielskatz that is probably right. It is not clear to me how this all gets put together in the end. I will close that issue.
